# Generated by Django 3.2.5 on 2021-08-04 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_post_image'),
        ('market', '0003_auto_20210802_1654'),
    ]

    operations = [
    ]
