# Generated by Django 3.2.5 on 2021-08-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_comment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
    ]
