# Generated by Django 3.2.5 on 2021-08-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_post_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
    ]
